### ISSUE TITLE
update-alternatives: warning: forcing reinstallation of alternative /usr/bin/php7.4 because link group php is broken update-alternatives: warning: skip creation of /usr/share/man/man1/php.1.gz because associated file /usr/share/man/man1/php7.4.1.gz (of link group php) doesn't exist

### ISSUE THREAD

**Issue by sufiyanpk7** [MAD-I-T/magento-actions#8]
![image](https://user-images.githubusercontent.com/45423403/128336476-1da9d259-27bf-4b3e-8e87-5952d3c0515b.png)

**Comment by seyuf** [comment]
Hi @sufiyanpk7,
 
Thanks for the feedback, even though more info would be appreciated, for example, are you just talking about the php warning ? 
Because on your screenshot, there seems to be also an issue related a missing build.sh script.

Regards

**Comment by sufiyanpk7** [comment]
yes the PHP warning causing build error,
![image](https://user-images.githubusercontent.com/45423403/128597576-f26ce9f6-d366-4b1e-8bb7-88a5f822798e.png)
![image](https://user-images.githubusercontent.com/45423403/128597663-79460627-4f24-49aa-8fb1-01b068f0b59d.png)

**Comment by sufiyanpk7** [comment]
> Hi @sufiyanpk7,
> 
> Thanks for the feedback, even though more info would be appreciated, for example, are you just talking about the php warning ?
> Because on your screenshot, there seems to be also an issue related a missing build.sh script.
> 
> Regards

tried again with https://github.com/MAD-I-T/magento-actions/commit/f682e53274f9815c704a818a687b30b9e1501be3 still no luck

**Comment by seyuf** [comment]
@sufiyanpk7 the php error is just a warning because the man docs was being dropped.
It should have not impact on the build process? From your screenshot you seem to have a missing script (/opt/scripts/build.sh)
Anyways, i fixed the php error (in the latest commit) but unfortunately dockerhub does no longer support autobuild which is why you're still seeing the error. We're in the process of migrating to github registry anyways. I'll let you know when the fixed image is up.

**Comment by sufiyanpk7** [comment]
Okay thanks @seyuf

**Comment by seyuf** [comment]
@sufiyanpk7 just deployed a new version using ghrc.io as registry.
The error should be fixed there (e.g **MAD-I-T/magento-actions@v3.3** )
Enjoy ;)

**Comment by sufiyanpk7** [comment]
Okay thanks 😍
